var $protobuf=require("protobufjs/minimal"),$Reader=$protobuf.Reader,$Writer=$protobuf.Writer,$util=$protobuf.util,$root=$protobuf.roots["default"]||($protobuf.roots["default"]={});
$root.textsecure=function(){var f={};f.WhisperMessage=function(){function d(a){if(a)for(var b=Object.keys(a),c=0;c<b.length;++c)null!=a[b[c]]&&(this[b[c]]=a[b[c]])}d.prototype.ephemeralKey=$util.newBuffer([]);d.prototype.counter=0;d.prototype.previousCounter=0;d.prototype.ciphertext=$util.newBuffer([]);d.create=function(a){return new d(a)};d.encode=function(a,b){b||=$Writer.create();null!=a.ephemeralKey&&a.hasOwnProperty("ephemeralKey")&&b.uint32(10).bytes(a.ephemeralKey);null!=a.counter&&a.hasOwnProperty("counter")&&
b.uint32(16).uint32(a.counter);null!=a.previousCounter&&a.hasOwnProperty("previousCounter")&&b.uint32(24).uint32(a.previousCounter);null!=a.ciphertext&&a.hasOwnProperty("ciphertext")&&b.uint32(34).bytes(a.ciphertext);return b};d.encodeDelimited=function(a,b){return this.encode(a,b).ldelim()};d.decode=function(a,b){a instanceof $Reader||(a=$Reader.create(a));b=void 0===b?a.len:a.pos+b;for(var c=new $root.textsecure.WhisperMessage;a.pos<b;){var e=a.uint32();switch(e>>>3){case 1:c.ephemeralKey=a.bytes();
break;case 2:c.counter=a.uint32();break;case 3:c.previousCounter=a.uint32();break;case 4:c.ciphertext=a.bytes();break;default:a.skipType(e&7)}}return c};d.decodeDelimited=function(a){a instanceof $Reader||(a=new $Reader(a));return this.decode(a,a.uint32())};d.verify=function(a){return"object"!==typeof a||null===a?"object expected":null==a.ephemeralKey||!a.hasOwnProperty("ephemeralKey")||a.ephemeralKey&&"number"===typeof a.ephemeralKey.length||$util.isString(a.ephemeralKey)?null!=a.counter&&a.hasOwnProperty("counter")&&
!$util.isInteger(a.counter)?"counter: integer expected":null!=a.previousCounter&&a.hasOwnProperty("previousCounter")&&!$util.isInteger(a.previousCounter)?"previousCounter: integer expected":null==a.ciphertext||!a.hasOwnProperty("ciphertext")||a.ciphertext&&"number"===typeof a.ciphertext.length||$util.isString(a.ciphertext)?null:"ciphertext: buffer expected":"ephemeralKey: buffer expected"};d.fromObject=function(a){if(a instanceof $root.textsecure.WhisperMessage)return a;var b=new $root.textsecure.WhisperMessage;
null!=a.ephemeralKey&&("string"===typeof a.ephemeralKey?$util.base64.decode(a.ephemeralKey,b.ephemeralKey=$util.newBuffer($util.base64.length(a.ephemeralKey)),0):a.ephemeralKey.length&&(b.ephemeralKey=a.ephemeralKey));null!=a.counter&&(b.counter=a.counter>>>0);null!=a.previousCounter&&(b.previousCounter=a.previousCounter>>>0);null!=a.ciphertext&&("string"===typeof a.ciphertext?$util.base64.decode(a.ciphertext,b.ciphertext=$util.newBuffer($util.base64.length(a.ciphertext)),0):a.ciphertext.length&&
(b.ciphertext=a.ciphertext));return b};d.toObject=function(a,b){b||={};var c={};b.defaults&&(b.bytes===String?c.ephemeralKey="":(c.ephemeralKey=[],b.bytes!==Array&&(c.ephemeralKey=$util.newBuffer(c.ephemeralKey))),c.counter=0,c.previousCounter=0,b.bytes===String?c.ciphertext="":(c.ciphertext=[],b.bytes!==Array&&(c.ciphertext=$util.newBuffer(c.ciphertext))));null!=a.ephemeralKey&&a.hasOwnProperty("ephemeralKey")&&(c.ephemeralKey=b.bytes===String?$util.base64.encode(a.ephemeralKey,0,a.ephemeralKey.length):
b.bytes===Array?Array.prototype.slice.call(a.ephemeralKey):a.ephemeralKey);null!=a.counter&&a.hasOwnProperty("counter")&&(c.counter=a.counter);null!=a.previousCounter&&a.hasOwnProperty("previousCounter")&&(c.previousCounter=a.previousCounter);null!=a.ciphertext&&a.hasOwnProperty("ciphertext")&&(c.ciphertext=b.bytes===String?$util.base64.encode(a.ciphertext,0,a.ciphertext.length):b.bytes===Array?Array.prototype.slice.call(a.ciphertext):a.ciphertext);return c};d.prototype.toJSON=function(){return this.constructor.toObject(this,
$protobuf.util.toJSONOptions)};return d}();f.PreKeyWhisperMessage=function(){function d(a){if(a)for(var b=Object.keys(a),c=0;c<b.length;++c)null!=a[b[c]]&&(this[b[c]]=a[b[c]])}d.prototype.registrationId=0;d.prototype.preKeyId=0;d.prototype.signedPreKeyId=0;d.prototype.baseKey=$util.newBuffer([]);d.prototype.identityKey=$util.newBuffer([]);d.prototype.message=$util.newBuffer([]);d.create=function(a){return new d(a)};d.encode=function(a,b){b||=$Writer.create();null!=a.preKeyId&&a.hasOwnProperty("preKeyId")&&
b.uint32(8).uint32(a.preKeyId);null!=a.baseKey&&a.hasOwnProperty("baseKey")&&b.uint32(18).bytes(a.baseKey);null!=a.identityKey&&a.hasOwnProperty("identityKey")&&b.uint32(26).bytes(a.identityKey);null!=a.message&&a.hasOwnProperty("message")&&b.uint32(34).bytes(a.message);null!=a.registrationId&&a.hasOwnProperty("registrationId")&&b.uint32(40).uint32(a.registrationId);null!=a.signedPreKeyId&&a.hasOwnProperty("signedPreKeyId")&&b.uint32(48).uint32(a.signedPreKeyId);return b};d.encodeDelimited=function(a,
b){return this.encode(a,b).ldelim()};d.decode=function(a,b){a instanceof $Reader||(a=$Reader.create(a));b=void 0===b?a.len:a.pos+b;for(var c=new $root.textsecure.PreKeyWhisperMessage;a.pos<b;){var e=a.uint32();switch(e>>>3){case 5:c.registrationId=a.uint32();break;case 1:c.preKeyId=a.uint32();break;case 6:c.signedPreKeyId=a.uint32();break;case 2:c.baseKey=a.bytes();break;case 3:c.identityKey=a.bytes();break;case 4:c.message=a.bytes();break;default:a.skipType(e&7)}}return c};d.decodeDelimited=function(a){a instanceof
$Reader||(a=new $Reader(a));return this.decode(a,a.uint32())};d.verify=function(a){return"object"!==typeof a||null===a?"object expected":null!=a.registrationId&&a.hasOwnProperty("registrationId")&&!$util.isInteger(a.registrationId)?"registrationId: integer expected":null!=a.preKeyId&&a.hasOwnProperty("preKeyId")&&!$util.isInteger(a.preKeyId)?"preKeyId: integer expected":null!=a.signedPreKeyId&&a.hasOwnProperty("signedPreKeyId")&&!$util.isInteger(a.signedPreKeyId)?"signedPreKeyId: integer expected":
null==a.baseKey||!a.hasOwnProperty("baseKey")||a.baseKey&&"number"===typeof a.baseKey.length||$util.isString(a.baseKey)?null==a.identityKey||!a.hasOwnProperty("identityKey")||a.identityKey&&"number"===typeof a.identityKey.length||$util.isString(a.identityKey)?null==a.message||!a.hasOwnProperty("message")||a.message&&"number"===typeof a.message.length||$util.isString(a.message)?null:"message: buffer expected":"identityKey: buffer expected":"baseKey: buffer expected"};d.fromObject=function(a){if(a instanceof
$root.textsecure.PreKeyWhisperMessage)return a;var b=new $root.textsecure.PreKeyWhisperMessage;null!=a.registrationId&&(b.registrationId=a.registrationId>>>0);null!=a.preKeyId&&(b.preKeyId=a.preKeyId>>>0);null!=a.signedPreKeyId&&(b.signedPreKeyId=a.signedPreKeyId>>>0);null!=a.baseKey&&("string"===typeof a.baseKey?$util.base64.decode(a.baseKey,b.baseKey=$util.newBuffer($util.base64.length(a.baseKey)),0):a.baseKey.length&&(b.baseKey=a.baseKey));null!=a.identityKey&&("string"===typeof a.identityKey?
$util.base64.decode(a.identityKey,b.identityKey=$util.newBuffer($util.base64.length(a.identityKey)),0):a.identityKey.length&&(b.identityKey=a.identityKey));null!=a.message&&("string"===typeof a.message?$util.base64.decode(a.message,b.message=$util.newBuffer($util.base64.length(a.message)),0):a.message.length&&(b.message=a.message));return b};d.toObject=function(a,b){b||={};var c={};b.defaults&&(c.preKeyId=0,b.bytes===String?c.baseKey="":(c.baseKey=[],b.bytes!==Array&&(c.baseKey=$util.newBuffer(c.baseKey))),
b.bytes===String?c.identityKey="":(c.identityKey=[],b.bytes!==Array&&(c.identityKey=$util.newBuffer(c.identityKey))),b.bytes===String?c.message="":(c.message=[],b.bytes!==Array&&(c.message=$util.newBuffer(c.message))),c.registrationId=0,c.signedPreKeyId=0);null!=a.preKeyId&&a.hasOwnProperty("preKeyId")&&(c.preKeyId=a.preKeyId);null!=a.baseKey&&a.hasOwnProperty("baseKey")&&(c.baseKey=b.bytes===String?$util.base64.encode(a.baseKey,0,a.baseKey.length):b.bytes===Array?Array.prototype.slice.call(a.baseKey):
a.baseKey);null!=a.identityKey&&a.hasOwnProperty("identityKey")&&(c.identityKey=b.bytes===String?$util.base64.encode(a.identityKey,0,a.identityKey.length):b.bytes===Array?Array.prototype.slice.call(a.identityKey):a.identityKey);null!=a.message&&a.hasOwnProperty("message")&&(c.message=b.bytes===String?$util.base64.encode(a.message,0,a.message.length):b.bytes===Array?Array.prototype.slice.call(a.message):a.message);null!=a.registrationId&&a.hasOwnProperty("registrationId")&&(c.registrationId=a.registrationId);
null!=a.signedPreKeyId&&a.hasOwnProperty("signedPreKeyId")&&(c.signedPreKeyId=a.signedPreKeyId);return c};d.prototype.toJSON=function(){return this.constructor.toObject(this,$protobuf.util.toJSONOptions)};return d}();f.KeyExchangeMessage=function(){function d(a){if(a)for(var b=Object.keys(a),c=0;c<b.length;++c)null!=a[b[c]]&&(this[b[c]]=a[b[c]])}d.prototype.id=0;d.prototype.baseKey=$util.newBuffer([]);d.prototype.ephemeralKey=$util.newBuffer([]);d.prototype.identityKey=$util.newBuffer([]);d.prototype.baseKeySignature=
$util.newBuffer([]);d.create=function(a){return new d(a)};d.encode=function(a,b){b||=$Writer.create();null!=a.id&&a.hasOwnProperty("id")&&b.uint32(8).uint32(a.id);null!=a.baseKey&&a.hasOwnProperty("baseKey")&&b.uint32(18).bytes(a.baseKey);null!=a.ephemeralKey&&a.hasOwnProperty("ephemeralKey")&&b.uint32(26).bytes(a.ephemeralKey);null!=a.identityKey&&a.hasOwnProperty("identityKey")&&b.uint32(34).bytes(a.identityKey);null!=a.baseKeySignature&&a.hasOwnProperty("baseKeySignature")&&b.uint32(42).bytes(a.baseKeySignature);
return b};d.encodeDelimited=function(a,b){return this.encode(a,b).ldelim()};d.decode=function(a,b){a instanceof $Reader||(a=$Reader.create(a));b=void 0===b?a.len:a.pos+b;for(var c=new $root.textsecure.KeyExchangeMessage;a.pos<b;){var e=a.uint32();switch(e>>>3){case 1:c.id=a.uint32();break;case 2:c.baseKey=a.bytes();break;case 3:c.ephemeralKey=a.bytes();break;case 4:c.identityKey=a.bytes();break;case 5:c.baseKeySignature=a.bytes();break;default:a.skipType(e&7)}}return c};d.decodeDelimited=function(a){a instanceof
$Reader||(a=new $Reader(a));return this.decode(a,a.uint32())};d.verify=function(a){return"object"!==typeof a||null===a?"object expected":null!=a.id&&a.hasOwnProperty("id")&&!$util.isInteger(a.id)?"id: integer expected":null==a.baseKey||!a.hasOwnProperty("baseKey")||a.baseKey&&"number"===typeof a.baseKey.length||$util.isString(a.baseKey)?null==a.ephemeralKey||!a.hasOwnProperty("ephemeralKey")||a.ephemeralKey&&"number"===typeof a.ephemeralKey.length||$util.isString(a.ephemeralKey)?null==a.identityKey||
!a.hasOwnProperty("identityKey")||a.identityKey&&"number"===typeof a.identityKey.length||$util.isString(a.identityKey)?null==a.baseKeySignature||!a.hasOwnProperty("baseKeySignature")||a.baseKeySignature&&"number"===typeof a.baseKeySignature.length||$util.isString(a.baseKeySignature)?null:"baseKeySignature: buffer expected":"identityKey: buffer expected":"ephemeralKey: buffer expected":"baseKey: buffer expected"};d.fromObject=function(a){if(a instanceof $root.textsecure.KeyExchangeMessage)return a;
var b=new $root.textsecure.KeyExchangeMessage;null!=a.id&&(b.id=a.id>>>0);null!=a.baseKey&&("string"===typeof a.baseKey?$util.base64.decode(a.baseKey,b.baseKey=$util.newBuffer($util.base64.length(a.baseKey)),0):a.baseKey.length&&(b.baseKey=a.baseKey));null!=a.ephemeralKey&&("string"===typeof a.ephemeralKey?$util.base64.decode(a.ephemeralKey,b.ephemeralKey=$util.newBuffer($util.base64.length(a.ephemeralKey)),0):a.ephemeralKey.length&&(b.ephemeralKey=a.ephemeralKey));null!=a.identityKey&&("string"===
typeof a.identityKey?$util.base64.decode(a.identityKey,b.identityKey=$util.newBuffer($util.base64.length(a.identityKey)),0):a.identityKey.length&&(b.identityKey=a.identityKey));null!=a.baseKeySignature&&("string"===typeof a.baseKeySignature?$util.base64.decode(a.baseKeySignature,b.baseKeySignature=$util.newBuffer($util.base64.length(a.baseKeySignature)),0):a.baseKeySignature.length&&(b.baseKeySignature=a.baseKeySignature));return b};d.toObject=function(a,b){b||={};var c={};b.defaults&&(c.id=0,b.bytes===
String?c.baseKey="":(c.baseKey=[],b.bytes!==Array&&(c.baseKey=$util.newBuffer(c.baseKey))),b.bytes===String?c.ephemeralKey="":(c.ephemeralKey=[],b.bytes!==Array&&(c.ephemeralKey=$util.newBuffer(c.ephemeralKey))),b.bytes===String?c.identityKey="":(c.identityKey=[],b.bytes!==Array&&(c.identityKey=$util.newBuffer(c.identityKey))),b.bytes===String?c.baseKeySignature="":(c.baseKeySignature=[],b.bytes!==Array&&(c.baseKeySignature=$util.newBuffer(c.baseKeySignature))));null!=a.id&&a.hasOwnProperty("id")&&
(c.id=a.id);null!=a.baseKey&&a.hasOwnProperty("baseKey")&&(c.baseKey=b.bytes===String?$util.base64.encode(a.baseKey,0,a.baseKey.length):b.bytes===Array?Array.prototype.slice.call(a.baseKey):a.baseKey);null!=a.ephemeralKey&&a.hasOwnProperty("ephemeralKey")&&(c.ephemeralKey=b.bytes===String?$util.base64.encode(a.ephemeralKey,0,a.ephemeralKey.length):b.bytes===Array?Array.prototype.slice.call(a.ephemeralKey):a.ephemeralKey);null!=a.identityKey&&a.hasOwnProperty("identityKey")&&(c.identityKey=b.bytes===
String?$util.base64.encode(a.identityKey,0,a.identityKey.length):b.bytes===Array?Array.prototype.slice.call(a.identityKey):a.identityKey);null!=a.baseKeySignature&&a.hasOwnProperty("baseKeySignature")&&(c.baseKeySignature=b.bytes===String?$util.base64.encode(a.baseKeySignature,0,a.baseKeySignature.length):b.bytes===Array?Array.prototype.slice.call(a.baseKeySignature):a.baseKeySignature);return c};d.prototype.toJSON=function(){return this.constructor.toObject(this,$protobuf.util.toJSONOptions)};return d}();
return f}();module.exports=$root;
